name: "Pogoda"

on:
  workflow_dispatch:
    inputs:
      miasto:
        description: "Miasto"
        required: true
        default: "Warszawa"

jobs:
  pogoda_dla_miast:
    name: "Pogoda dla miast"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Run Script"
        run: |
          bash ./start.sh "${{github.event.inputs.miasto}}" "${{secrets.OPEN_WEATHER_API_KEY}}" >> $GITHUB_STEP_SUMMARY